language: node_js
node_js:
- '12'
script:
- yarn test
before_deploy: 'cd directory && yarn && yarn build && cd ..'
deploy:
  - provider: npm
    skip_cleanup: true
    email: brandon@heylo.co
    api_key:
      secure: 'Bbk1OEPh68TN8FlvajWXW3kfe6jvGA9NEmh7ExCbd/+KXX2SjDwhTirPGXLUV57oDmO0xooWFNcNltYAczNJzBGx4yMh1wwG85mWIBhZJ7YhBPstZXJN91Hm9l9yJ1gn7iLmjw1m7sWZijFYFCcEGkPhRS5ySQI8eaget6luNecXsUOsjM5ixztJCyowfc5mlxwcNZpqYDRRZWk+nQ20eSRFg26DrGbu5rxXw6+wyk4sZ3H3YuD8Nnu98y8lPHp2J55B6/sNTpkKzbX2dXxoHOknuKXtKy30936YGl7P9yWSJrdlmnl2hMMCCrLP9WCwL1zXfWPwuJcTRQMIOZ38bklgJlCVol3ivgVShZj3UCB6cuF728/9rgBLDOYQvMYSRTBxF1VzaN+XbvQibRSE8rwr9bdxSQlWCiticSjVQYd5cesOvn6hGzxrJquQOYqgNf0fF+JBjUEM5tT8VSb6jjs/gXWaFkjOcDsZa6fgQWroOFr/rC0SNEWIKKf+TCjJ7Wwjlb5ivVendlwosGf7hh5umgXYZhQaZUPNv14V6j7Yse3QHu0k5wXeFKWmEQ/71p/1TSapgPViSM5jeWDeGZ7qgaeLnkZKSLCdvaB0Cp3fI+J8j0nSIYzNk9uGcFPVwSzD1KxaQswOvjA3WhypmcBwP0tKeV3vpJyohaMYzow='
    on:
      tags: true
      repo: brandonpearcy/react-native-vector-icons
